# Generated by Django 5.2.3 on 2025-06-12 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='newletter_abo',
            field=models.BooleanField(default=False),
        ),
    ]
