# Generated by Django 5.2.3 on 2025-06-12 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_app', '0002_customer_newletter_abo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='account',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='email_adress',
            field=models.CharField(blank=True, default=''),
        ),
    ]
