# Generated by Django 5.2.3 on 2025-06-17 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_app', '0005_bill_product_order_producttype_order_products'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['last_name'], 'verbose_name': 'Customer', 'verbose_name_plural': 'Costomerse'},
        ),
        migrations.AddField(
            model_name='customer',
            name='slug',
            field=models.SlugField(blank=True, default=''),
        ),
    ]
