# Generated by Django 5.2.3 on 2025-06-21 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_app', '0006_alter_customer_options_customer_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={},
        ),
        migrations.RemoveField(
            model_name='customer',
            name='slug',
        ),
    ]
